version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_evaluacion
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - evaluacion_net

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: backend_evaluacion
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    networks:
      - evaluacion_net

  frontend:
    image: nginx:alpine
    container_name: frontend_evaluacion
    volumes:
      - ../frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - evaluacion_net

volumes:
  sqlserver_data:

networks:
  evaluacion_net:
    driver: bridge
