services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_evaluacion
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - evaluacion_net

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: backend_evaluacion
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=evaluacion_parcial_2_db;User Id=sa;Password=Password123!;TrustServerCertificate=True;
      - Jwt__Clave=CLAVE_SUPER_SECRETA_EVALUACION_2026_CAMBIAR_EN_PRODUCCION
      - Jwt__Emisor=EvaluacionParcial2
      - Jwt__Audiencia=EvaluacionParcial2Usuarios
      - Jwt__MinutosExpiracion=120
    networks:
      - evaluacion_net

  frontend:
    image: nginx:alpine
    container_name: frontend_evaluacion
    volumes:
      - ../frontend-angular/dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - evaluacion_net

volumes:
  sqlserver_data:

networks:
  evaluacion_net:
    driver: bridge